import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f9f7ff',
  '--slot4-page-text': '#150f41',
  '--slot4-panel-bg': '#edecf8',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#5d6c7b',
  '--slot4-soft-muted-text': '#758696',
  '--slot4-accent': '#4760e6',
  '--slot4-accent-fill': '#4760e6',
  '--slot4-accent-soft': '#eef0fd',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#150f41',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#edecf8',
  '--slot4-cream': '#f9f7ff',
  '--slot4-warm': '#f4f2fc',
  '--slot4-lavender': '#edecf8',
  '--slot4-gray': '#f4f2fc',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f9f7ff',
  '--editable-page-text': '#150f41',
  '--editable-container': '1400px',
  '--editable-border': '#e6e5f5',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#150f41',
  '--editable-nav-active': '#4760e6',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#4760e6',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#150f41',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_2px_8px_rgba(21,15,65,0.06)]',
  shadowStrong: 'shadow-[0_8px_32px_rgba(21,15,65,0.12)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(21,15,65,0.02),rgba(21,15,65,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[1400px] px-5 sm:px-8 lg:px-[60px]',
    sectionY: 'py-12 sm:py-16 lg:py-24',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-sm font-semibold uppercase tracking-[0.14em] text-[var(--slot4-accent)]',
    heroTitle: 'text-[40px] font-bold leading-[1.08] tracking-[-0.02em] sm:text-5xl lg:text-[64px]',
    sectionTitle: 'text-[32px] font-bold tracking-[-0.02em] sm:text-[40px]',
    body: 'text-base leading-relaxed sm:text-lg lg:text-xl',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--slot4-accent-fill)] px-7 py-3.5 text-[15px] font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:bg-[#4259d9] active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-xl border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3.5 text-[15px] font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-xl ${editablePalette.accentBg} px-7 py-3.5 text-[15px] font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:bg-[#4259d9] active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1.5 hover:shadow-[0_16px_48px_rgba(21,15,65,0.14)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
